require "openssl"
require "digest"
require "json"
require "base64"
require "aws-sdk-kms"

# Envelope encryption service for customer signing credentials.
#
# Each encrypted value gets its own DEK (data encryption key) generated by AWS KMS.
# The DEK encrypts the payload via AES-256-GCM locally; KMS only ever sees the DEK
# itself, never the customer's `.p8`/SA-JSON/keystore bytes. The wrapped DEK + the
# ciphertext + IV + auth_tag are stored together as an "envelope" on the record.
#
# The +context+ Hash binds each ciphertext to its owning record at two layers:
#
#   1. KMS +EncryptionContext+ — KMS refuses to decrypt the wrapped DEK if the
#      context differs from what was supplied at encrypt time.
#   2. AES-GCM +auth_data+ — even if an attacker managed to convince KMS to
#      unwrap the DEK (e.g. by swapping wrapped DEKs between rows), the AES-GCM
#      authentication tag won't validate, and decrypt raises +DecryptError+.
#
# This double binding is what prevents an attacker with read access to the DB
# from re-targeting wrapped DEKs across records.
#
# Required context keys: +org_id+, +credential_kind+, +credential_id+ (all strings).
#
# Typical use:
#
#   envelope = CredentialVault.encrypt(plaintext_p8_pem, context: {
#     org_id: org.id.to_s,
#     credential_kind: "asc",
#     credential_id: credential.id.to_s
#   })
#   # Persist envelope.{ciphertext,wrapped_dek,iv,auth_tag,key_id,alg_version} on the row.
#
#   plaintext = CredentialVault.decrypt(envelope, context: same_context)
#
# Configuration:
#
#   - ENV +AWS_ACCESS_KEY_ID+, +AWS_SECRET_ACCESS_KEY+, +AWS_REGION+ — picked up
#     by the AWS SDK automatically.
#   - ENV +MYSIGNER_KMS_KEY_ARN+ — the CMK alias or ARN this vault writes to.
class CredentialVault
  class Error              < StandardError; end
  class ConfigurationError < Error;        end
  class DecryptError       < Error;        end
  # Raised when decrypt fails because the customer's BYOK CMK has become
  # unreachable: either their key policy no longer grants our principal access
  # (AccessDeniedException) or the key is Disabled / PendingDeletion
  # (KMSInvalidStateException). Distinct from InvalidCiphertextException —
  # that signals tampering or context mismatch, not revocation. Inherits from
  # DecryptError so existing `rescue DecryptError` callers continue to catch
  # it; new callers (the ApplicationController rescue_from) discriminate via
  # this subclass and surface an actionable 403 to the operator.
  # mysigner-21 sub-ticket 2.4.
  class CustomerKeyRevoked < DecryptError; end

  # Bumping CURRENT_ALG lets us migrate cipher choice later without breaking
  # already-stored envelopes. Decrypt reads +envelope.alg_version+ to pick
  # the right code path; for now there is only one.
  ALG_AES_256_GCM_KMS_V1 = 1
  CURRENT_ALG            = ALG_AES_256_GCM_KMS_V1

  REQUIRED_CONTEXT_KEYS  = %w[org_id credential_kind credential_id].freeze

  Envelope = Struct.new(
    :ciphertext, :wrapped_dek, :iv, :auth_tag, :key_id, :alg_version,
    keyword_init: true
  )

  class << self
    attr_writer :kms_client, :key_arn

    # Encrypt +plaintext+ under a fresh KMS-wrapped DEK.
    # @param plaintext [String] raw bytes to encrypt
    # @param context [Hash] must contain :org_id, :credential_kind, :credential_id
    # @param key_arn [String, nil] override CMK ARN (used by BYOK to wrap DEKs
    #   under the customer's CMK). When nil, falls back to the env-default CMK.
    #   The envelope's `key_id` reflects whichever CMK KMS actually used, so
    #   decrypt routes back to it automatically without a second lookup.
    # @return [Envelope]
    def encrypt(plaintext, context:, key_arn: nil)
      str_context = stringify_context(context)
      validate_context!(str_context)

      effective_key_arn = key_arn || self.key_arn

      dek = kms_client.generate_data_key(
        key_id:             effective_key_arn,
        key_spec:           "AES_256",
        encryption_context: str_context
      )

      cipher = OpenSSL::Cipher.new("aes-256-gcm").encrypt
      cipher.key       = dek.plaintext
      iv               = cipher.random_iv
      cipher.auth_data = aad(str_context)
      ciphertext       = cipher.update(plaintext) + cipher.final

      Envelope.new(
        ciphertext:  ciphertext,
        wrapped_dek: dek.ciphertext_blob,
        iv:          iv,
        auth_tag:    cipher.auth_tag,
        key_id:      dek.key_id,
        alg_version: CURRENT_ALG
      )
    end

    # Decrypt an Envelope back to its plaintext.
    # Raises +DecryptError+ if context mismatches at either KMS or AES-GCM.
    # @param envelope [Envelope]
    # @param context [Hash] must match what was passed to .encrypt
    # @return [String] the original plaintext bytes
    # +audit:+ — pass false for operational/bulk decrypts (e.g. the pre-flight
    # EnvelopeVerifier sweep) so they don't flood the forensic audit log with
    # non-"use" decrypt rows (and incur a per-record org lookup). Real job/use
    # decrypts leave it true.
    def decrypt(envelope, context:, audit: true)
      str_context = stringify_context(context)
      validate_context!(str_context)

      unless envelope.alg_version == ALG_AES_256_GCM_KMS_V1
        raise Error, "unsupported alg_version=#{envelope.alg_version.inspect}"
      end

      dek = unwrap_dek(envelope.wrapped_dek, envelope.key_id, str_context)

      cipher = OpenSSL::Cipher.new("aes-256-gcm").decrypt
      cipher.key       = dek
      cipher.iv        = envelope.iv
      cipher.auth_tag  = envelope.auth_tag
      cipher.auth_data = aad(str_context)
      plaintext = cipher.update(envelope.ciphertext) + cipher.final

      # L-19: audit the decrypt at the vault boundary so background-job decrypts
      # (which never hit a controller) leave a trail. Cheap and strictly
      # non-fatal — `audit_decrypt` swallows every error so an audit hiccup can
      # never break a credential decrypt. Controllers already emit their own
      # richer, kind-specific audit events; this is the safety net for the
      # actor-less job path.
      audit_decrypt(str_context) if audit

      plaintext
    rescue OpenSSL::Cipher::CipherError
      # AES-GCM auth_tag verification failed. Either the context Hash differs
      # from the one used at encrypt time, or the ciphertext/IV/tag were
      # tampered with at rest.
      raise DecryptError, "ciphertext integrity check failed (context mismatch or tampered envelope)"
    rescue Aws::KMS::Errors::AccessDeniedException => e
      # KMS refused to unwrap. The same AWS error class fires for two very
      # different operational situations and we MUST distinguish them — see
      # `customer_managed_envelope?` below. Misclassifying an internal
      # MySigner-side incident as a BYOK customer revocation would (a) emit
      # `byok_kms_key_revoked_detected` against an org whose CMK had nothing
      # to do with the failure, and (b) mask the real internal incident.
      if customer_managed_envelope?(envelope)
        raise CustomerKeyRevoked, "customer CMK access denied: #{e.message}"
      else
        raise DecryptError, "KMS access denied for env-default CMK (likely an internal MySigner incident, not BYOK): #{e.message}"
      end
    rescue Aws::KMS::Errors::KMSInvalidStateException => e
      # Same dual-meaning gating as AccessDeniedException: a Disabled or
      # PendingDeletion state on the env-default CMK is an internal incident;
      # on a customer's CMK it's BYOK revocation.
      if customer_managed_envelope?(envelope)
        raise CustomerKeyRevoked, "customer CMK is disabled or pending deletion: #{e.message}"
      else
        raise DecryptError, "env-default CMK is disabled or pending deletion (internal incident): #{e.message}"
      end
    rescue Aws::KMS::Errors::InvalidCiphertextException
      # KMS refused to unwrap the DEK — usually a context mismatch, sometimes
      # a wrong CMK (e.g. envelope from a different environment). NOT a
      # revocation signal: keep this branch AFTER the BYOK-specific rescues
      # so revoked-key cases don't get swallowed by the generic message.
      raise DecryptError, "KMS rejected wrapped DEK (context mismatch or wrong CMK)"
    end

    # Serialize an Envelope into a string suitable for storage in a text column.
    # Uses JSON with base64 for binary fields — easy to debug, language-agnostic,
    # and ~33% bloat from base64 is fine for ~500-byte envelopes.
    # Keys are intentionally short ("v", "kid", "ct", "dek", "iv", "tag") to
    # keep the at-rest size down without losing readability.
    def pack(envelope)
      {
        "v"   => envelope.alg_version,
        "kid" => envelope.key_id,
        "ct"  => Base64.strict_encode64(envelope.ciphertext),
        "dek" => Base64.strict_encode64(envelope.wrapped_dek),
        "iv"  => Base64.strict_encode64(envelope.iv),
        "tag" => Base64.strict_encode64(envelope.auth_tag)
      }.to_json
    end

    # Inverse of #pack — rebuild an Envelope from its serialized form.
    # Uses Hash#fetch so a missing field raises a clear KeyError rather than
    # silently producing an envelope with nil fields that would later fail
    # in OpenSSL with a less-obvious message.
    def unpack(packed)
      h = JSON.parse(packed)
      Envelope.new(
        alg_version: h.fetch("v"),
        key_id:      h.fetch("kid"),
        ciphertext:  Base64.strict_decode64(h.fetch("ct")),
        wrapped_dek: Base64.strict_decode64(h.fetch("dek")),
        iv:          Base64.strict_decode64(h.fetch("iv")),
        auth_tag:    Base64.strict_decode64(h.fetch("tag"))
      )
    end

    # True iff a KMS key ARN is configured (via setter or ENV). Used by the
    # Vaulted concern to no-op dual-write in test/dev environments that
    # haven't set up KMS, while crashing loudly in production via the
    # config/initializers/credential_vault.rb boot check.
    def configured?
      !@key_arn.nil? || !ENV["MYSIGNER_KMS_KEY_ARN"].nil?
    end

    # Liveness probe — call from a Rake task or health endpoint to confirm
    # the IAM principal can still reach the CMK and the key is Enabled.
    def healthy?
      kms_client.describe_key(key_id: key_arn).key_metadata.key_state == "Enabled"
    rescue Aws::KMS::Errors::ServiceError, ConfigurationError
      false
    end

    def kms_client
      @kms_client ||= Aws::KMS::Client.new
    end

    def key_arn
      @key_arn || ENV.fetch("MYSIGNER_KMS_KEY_ARN") do
        raise ConfigurationError, "MYSIGNER_KMS_KEY_ARN env var not set"
      end
    end

    # Evict the process-local cached plaintext DEK for a given wrapped DEK +
    # wrapping CMK. Used by OrgRewrap (L-1) to drop the OLD entry the instant
    # an envelope is rotated under a different CMK, so a rotated-away key can't
    # linger in RAM until its TTL expires. Safe to call for a key that was
    # never cached (no-op).
    def evict_dek(wrapped_dek, key_id)
      DekCache.delete(dek_cache_key(wrapped_dek, key_id))
    end

    private

    # True when the envelope's wrapping CMK is NOT MySigner's env-default CMK
    # — i.e. it was wrapped under a customer-managed (BYOK) CMK ARN. Used by
    # the decrypt rescue chain to distinguish "customer revoked their CMK"
    # (a BYOK-actionable 403) from "our IAM principal can't reach our own
    # CMK" (an internal MySigner-side incident). Misclassifying one as the
    # other would either mask an internal outage as a customer issue OR
    # emit a `byok_kms_key_revoked_detected` audit row attributing the
    # failure to an org whose CMK had nothing to do with it.
    #
    # AWS returns the canonical ARN as `key_id` from `generate_data_key`, so
    # the comparison against `key_arn` (env-default ARN) is reliable as long
    # as the env var is set to the canonical form (aliases are not used in
    # MYSIGNER_KMS_KEY_ARN — see mysigner-29).
    def customer_managed_envelope?(envelope)
      # Delegates to the bare-key_id classifier so the "is this a BYOK CMK?"
      # rule lives in exactly one place (used both here for the revocation
      # rescue chain and by unwrap_dek for the M-2 short-TTL decision). When no
      # env-default is configured (test env), that helper returns true — we
      # treat the envelope as customer-managed and surface CustomerKeyRevoked
      # rather than silently downgrading to a generic DecryptError.
      customer_managed_key_id?(envelope.key_id)
    end

    def unwrap_dek(wrapped_dek, key_id, context)
      # Cache the unwrapped *plaintext* DEK so we don't hit KMS on every read.
      #
      # SECURITY (H-1 / M-2): the cache is PROCESS-LOCAL (CredentialVault::DekCache,
      # an in-RAM TTL+LRU map) — NOT Rails.cache. Rails.cache in production is
      # Solid Cache, an unencrypted Postgres table; caching plaintext key
      # material there would write DEKs to disk in the clear and defeat
      # envelope encryption entirely. Keeping DEKs in RAM means they never
      # leave the process and die with it.
      #
      # Keyed by wrapped_dek hash so two different envelopes share neither cache
      # slot nor DEK; rotating a record's wrapped DEK naturally orphans the old
      # entry (and OrgRewrap explicitly evicts it — L-1).
      #
      # Versioned key: bumping MYSIGNER_DEK_CACHE_VERSION (env var) makes every
      # cached DEK orphan instantly — the version segment changes, so old-version
      # entries can never be read again. This is how we purge the DEK cache
      # during an incident response (mysigner-31).
      cache_key = dek_cache_key(wrapped_dek, key_id)

      # BYOK (customer-managed CMK) DEKs use a much shorter TTL so a customer
      # revoking their CMK becomes fail-closed within ~90s rather than lingering
      # for an hour (M-2). Env-default-CMK DEKs keep the prior 1-hour TTL.
      ttl = customer_managed_key_id?(key_id) ? DekCache::BYOK_TTL : DekCache::DEFAULT_TTL

      DekCache.fetch(cache_key, ttl: ttl) do
        kms_client.decrypt(
          ciphertext_blob:    wrapped_dek,
          key_id:             key_id,
          encryption_context: context
        ).plaintext
      end
    end

    # The process-local DEK-cache key for a given wrapped DEK + wrapping CMK.
    # Used internally by unwrap_dek and by the public `evict_dek` (which
    # OrgRewrap calls to drop the OLD entry when it rotates an envelope away —
    # L-1). Includes the MYSIGNER_DEK_CACHE_VERSION segment so a version bump
    # orphans every entry.
    def dek_cache_key(wrapped_dek, key_id)
      "credential_vault:dek:v#{dek_cache_version}:#{key_id}:#{Digest::SHA256.hexdigest(wrapped_dek)}"
    end

    # True when +key_id+ is NOT MySigner's env-default CMK — i.e. a customer
    # (BYOK) CMK. Mirrors `customer_managed_envelope?` but operates on a bare
    # key_id (the value unwrap_dek already has) so we don't reconstruct an
    # envelope. When no env-default is configured (test env where the vault
    # isn't wired up) we treat the key as customer-managed so the conservative
    # short TTL applies.
    def customer_managed_key_id?(key_id)
      env_arn = @key_arn || ENV["MYSIGNER_KMS_KEY_ARN"]
      return true if env_arn.nil?

      key_id.to_s != env_arn.to_s
    end

    def validate_context!(context)
      missing = REQUIRED_CONTEXT_KEYS - context.keys
      raise ArgumentError, "context missing keys: #{missing.join(', ')}" if missing.any?

      blanks = REQUIRED_CONTEXT_KEYS.select { |k| context[k].to_s.empty? }
      raise ArgumentError, "context has blank values for: #{blanks.join(', ')}" if blanks.any?
    end

    def stringify_context(context)
      raise ArgumentError, "context must be a Hash" unless context.is_a?(Hash)

      context.to_h { |k, v| [ k.to_s, v.to_s ] }
    end

    def dek_cache_version
      ENV.fetch("MYSIGNER_DEK_CACHE_VERSION", "1")
    end

    # L-19: emit an audit event for a credential decrypt that happens OUTSIDE a
    # controller request — i.e. a background job (DeliveryJob, sign workers,
    # etc.) that has no Current.user actor. Controllers already emit their own
    # richer, kind-specific audit events on the request path, so to avoid
    # double-logging we only fire here when there is NO current user actor
    # (the job / system path). The actor is left nil, which Audit::Logger and
    # AuditEvent#actor_display render as "System".
    #
    # STRICTLY non-fatal: any failure (audit infra down, missing action in the
    # allowlist, Current not loaded, etc.) is swallowed so it can NEVER break a
    # credential decrypt. Audit::Logger#call already rescues internally; the
    # outer rescue here guards the path that reaches it (e.g. Current access).
    def audit_decrypt(str_context)
      return unless defined?(Audit::Logger)

      # Only the actor-less (background-job / system) path. If a user is in
      # scope, the controller layer owns the audit trail for this action.
      current_user = (Current.user if defined?(Current) && Current.respond_to?(:user))
      return if current_user

      Audit::Logger.log(
        action:   "credential_decrypted",
        metadata: {
          credential_kind: str_context["credential_kind"],
          credential_id:   str_context["credential_id"],
          via:             "background_job"
        },
        actor:        nil,            # system actor → renders as "System"
        organization: audit_organization_for(str_context),
        system_actor: true
      )
    rescue => e
      # Never let audit bookkeeping break a decrypt.
      Rails.logger.error("[CredentialVault] audit_decrypt failed (non-fatal): #{e.class}: #{e.message}") if defined?(Rails)
      nil
    end

    # Resolve the Organization for the audit row from the decrypt context's
    # org_id, without making the decrypt boundary mandatory-DB. Best-effort:
    # returns nil if the org can't be found or the model isn't loaded, in which
    # case Audit::Logger simply skips the write (still non-fatal).
    def audit_organization_for(str_context)
      org_id = str_context["org_id"]
      return nil if org_id.to_s.empty?
      return nil unless defined?(Organization)

      Organization.find_by(id: org_id)
    rescue => _e
      nil
    end

    # Deterministic AAD for AES-GCM. Sorting the context keys then JSON-encoding
    # ensures the same (k,v) pairs always produce the same auth_data, regardless
    # of how the caller ordered their Hash literal.
    def aad(context)
      context.sort.to_h.to_json
    end
  end
end
